{{- range $key, $value := .Values.network_policies.egress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $key }}-np
  namespace: {{ $key }}
spec:
  egress:
    - to:
        {{- range $i, $val := $value }}
        - namespaceSelector:
            matchLabels:
              {{ $val }}: networking
        {{- end }}
  podSelector: {}
  policyTypes:
    - Egress
{{- end }}