{{- range $key, $value := .Values.network_policies.ingress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $key }}-np
  namespace: {{ $key }}
spec:
  ingress:
    - from:
        {{- range $i, $val := $value }}
        - namespaceSelector:
            matchLabels:
              {{ $val }}: networking
        {{- end }}
  podSelector: {}
  policyTypes:
    - Ingress
{{- end }}